[package]
authors = ["Trent Shailer"]
edition = "2024"
license = "MIT OR Apache-2.0"
name = "api-helper"
rust-version = "1.85"
version = "0.1.0"

[dependencies]
axum = { version = "0.8", default-features = false, features = ["json", "macros"] }
tokio = { version = "1.45", default-features = false, features = ["sync"] }

tracing = "0.1"

bb8 = "0.9"
bb8-postgres = { version = "0.9" }
tokio-postgres = "0.7"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

thiserror = "2"

jsonwebtoken = { version = "9.3", features = ["use_pem"] }
reqwest = { version = "0.12", features = ["json"] }

[workspace.lints.rust]
"deprecated_in_future" = "warn"
"missing_docs" = "warn"
"rust_2018_idioms" = "warn"
"unused_qualifications" = "warn"

[workspace.lints.clippy]
"as_conversions" = "warn"
"cast_lossless" = "warn"
"inconsistent_struct_constructor" = "warn"
"todo" = "warn"
"unnecessary_self_imports" = "warn"
"use_self" = "warn"
